"""Localized copy generated by `BankruptcyAnalysisService`.

Everything this service produces as prose — missing items, warnings,
discussion points, chapter questions, next steps — reaches a human unchanged.
It travels through `CaseAnalysisDto` into `CaseContextDto`, and from there the
deterministic draft turns `next_steps` into the assistant's suggested-action
labels and `warnings` into `AssistantResponse.warnings`.

Until 4.2.0 all of it was hardcoded Spanish, so an English session received
Spanish action labels — one half of the language leak the live agent run
recorded (`changes/chat-modal-centered.md`, defect 3). The other half is a
model emitting labels in the wrong language, which is handled in the agent
prompts.

Kept as one flat catalogue rather than scattered across the service so that a
missing translation is visible by reading two columns, and so `ruff` and the
type checker see every key.

**`required_evidence` is deliberately absent.** Those strings are matched
word-by-word against `EVIDENCE_TYPE_LABELS` by
`BankruptcyAnalysisService._evidence_matches` to compute `evidence_score`;
translating one side without the other would silently zero that score. That is
a separate defect from this one and is left recorded rather than half-fixed.
"""

from __future__ import annotations

from app.core.i18n import Language

_COPY: dict[str, dict[Language, str]] = {
    # -- missing items ------------------------------------------------------
    "missing.marital_status": {
        "es": "Estado civil y composición del hogar",
        "en": "Marital status and household composition",
    },
    "missing.housing": {
        "es": "Situación de vivienda",
        "en": "Housing situation",
    },
    "missing.income": {
        "es": "Fuentes de ingreso",
        "en": "Income sources",
    },
    "missing.expenses": {
        "es": "Gastos mensuales",
        "en": "Monthly expenses",
    },
    "missing.debts": {
        "es": "Lista de acreedores y deudas",
        "en": "Creditor and debt list",
    },
    "missing.assets": {
        "es": "Bienes y activos",
        "en": "Property and assets",
    },
    "missing.evidence": {
        "es": "Documentos de respaldo",
        "en": "Supporting documents",
    },
    "missing.goal": {
        "es": "Meta principal y urgencia del cliente",
        "en": "The client's main goal and urgency",
    },
    # -- warnings -----------------------------------------------------------
    "warning.deficit": {
        "es": "El presupuesto refleja un déficit mensual.",
        "en": "The budget shows a monthly deficit.",
    },
    "warning.debt_to_income": {
        "es": "La deuda total es alta frente al ingreso bruto anual estimado.",
        "en": "Total debt is high relative to estimated annual gross income.",
    },
    "warning.delinquent": {
        "es": "Existen cuentas en atraso que deben revisarse con prioridad.",
        "en": "There are past-due accounts that should be reviewed first.",
    },
    "warning.lawsuit": {
        "es": "Se reportó una demanda, embargo o acción de cobro activa.",
        "en": "An active lawsuit, garnishment or collection action was reported.",
    },
    "warning.priority_debt": {
        "es": "Hay deudas prioritarias que pueden recibir tratamiento especial.",
        "en": "There are priority debts that may receive special treatment.",
    },
    "warning.urgent_collection": {
        "es": "El cliente identificó una situación de cobro urgente.",
        "en": "The client identified an urgent collection situation.",
    },
    "warning.recent_transfer": {
        "es": "Las transferencias recientes deben revelarse al abogado.",
        "en": "Recent transfers must be disclosed to the attorney.",
    },
    # -- discussion points --------------------------------------------------
    "discussion.spouse": {
        "es": "Confirmar si la información del cónyuge debe incluirse aunque no presente conjuntamente.",
        "en": "Confirm whether the spouse's information must be included even when not filing jointly.",
    },
    "discussion.jurisdiction": {
        "es": "Validar la residencia, jurisdicción y fecha potencial de presentación.",
        "en": "Verify residency, jurisdiction and the potential filing date.",
    },
    "discussion.exemptions": {
        "es": "Revisar límites, exenciones y resultados del means test con datos vigentes.",
        "en": "Review limits, exemptions and means-test results against current figures.",
    },
    "discussion.positive_cash_flow": {
        "es": "Existe flujo mensual positivo para discutir capacidad de pago.",
        "en": "There is positive monthly cash flow to discuss repayment capacity.",
    },
    "discussion.tight_cash_flow": {
        "es": "El flujo mensual es limitado o negativo y requiere validación documental.",
        "en": "Monthly cash flow is limited or negative and needs documentary validation.",
    },
    "discussion.secured_intent": {
        "es": "Definir la intención respecto a vivienda, vehículos y otras garantías.",
        "en": "Decide the intention regarding housing, vehicles and other collateral.",
    },
    # -- chapter 7 questions ------------------------------------------------
    "chapter7.means_test": {
        "es": "¿Qué resultado produce el means test vigente para Puerto Rico y el tamaño del hogar?",
        "en": "What result does the current means test produce for Puerto Rico and this household size?",
    },
    "chapter7.exemptions": {
        "es": "¿Qué bienes podrían estar protegidos por exenciones aplicables?",
        "en": "Which assets might be protected by applicable exemptions?",
    },
    "chapter7.transfers": {
        "es": "¿Existen transferencias, pagos preferentes o activos que requieran análisis adicional?",
        "en": "Are there transfers, preferential payments or assets that need further analysis?",
    },
    "chapter7.disposable_income": {
        "es": "¿El flujo disponible cambia el análisis de abuso o capacidad de pago?",
        "en": "Does the available cash flow change the abuse or repayment-capacity analysis?",
    },
    "chapter7.secured_debts": {
        "es": "¿Qué ocurriría con cada deuda garantizada y su propiedad asociada?",
        "en": "What would happen to each secured debt and the property tied to it?",
    },
    # -- chapter 13 questions -----------------------------------------------
    "chapter13.regular_income": {
        "es": "¿El ingreso es suficientemente regular para sostener un plan de tres a cinco años?",
        "en": "Is the income regular enough to sustain a three-to-five-year plan?",
    },
    "chapter13.arrears": {
        "es": "¿Qué atrasos de hipoteca, vehículo, contribuciones o manutención deben incluirse?",
        "en": "Which mortgage, vehicle, tax or support arrears must be included?",
    },
    "chapter13.estimated_payment": {
        "es": "¿Cuál sería el pago estimado luego de validar ingreso disponible y reclamaciones?",
        "en": "What would the estimated payment be after validating disposable income and claims?",
    },
    "chapter13.feasibility": {
        "es": "¿Qué ajustes verificables permitirían financiar un plan realista?",
        "en": "What verifiable adjustments would make a realistic plan affordable?",
    },
    "chapter13.joint_filing": {
        "es": "¿Cómo cambia el plan al presentar una petición conjunta?",
        "en": "How does the plan change when filing a joint petition?",
    },
    # -- next steps ---------------------------------------------------------
    "next.complete_item": {
        "es": "Completar: {item}.",
        "en": "Complete: {item}.",
    },
    "next.link_evidence": {
        "es": "Vincular cada cifra importante con un documento de respaldo.",
        "en": "Link every significant figure to a supporting document.",
    },
    "next.save_questions": {
        "es": "Guardar preguntas para discutir en la consulta con el abogado.",
        "en": "Save questions to raise in the consultation with the attorney.",
    },
    "next.review_summary": {
        "es": "Revisar el resumen financiero completo.",
        "en": "Review the complete financial summary.",
    },
    "next.confirm_completeness": {
        "es": "Confirmar que no falten acreedores, bienes ni transferencias.",
        "en": "Confirm that no creditors, assets or transfers are missing.",
    },
    "next.submit": {
        "es": "Enviar la solicitud al abogado para revisión.",
        "en": "Send the request to the attorney for review.",
    },
    "next.attorney_reviews_warnings": {
        "es": "El abogado debe revisar primero las alertas identificadas.",
        "en": "The attorney should review the flagged alerts first.",
    },
    "next.request_documents": {
        "es": "Solicitar los documentos faltantes antes de discutir una estrategia.",
        "en": "Request the missing documents before discussing a strategy.",
    },
    "next.schedule_consultation": {
        "es": "Programar una consulta para comparar alternativas disponibles.",
        "en": "Schedule a consultation to compare the available alternatives.",
    },
    "next.prepare_consultation": {
        "es": "Preparar la consulta con el abogado.",
        "en": "Prepare for the consultation with the attorney.",
    },
    "next.validate_forms": {
        "es": "Validar formularios oficiales y datos de means test vigentes.",
        "en": "Validate official forms and current means-test figures.",
    },
    "next.document_decision": {
        "es": "Documentar la decisión profesional y los próximos pasos.",
        "en": "Record the professional decision and the next steps.",
    },
}


def copy(key: str, language: Language) -> str:
    """One catalogue entry, in the requested language.

    A missing key is a programming error, so it raises rather than returning
    the key itself — a `KeyError` in a test beats a raw `next.submit` rendered
    to a client.
    """
    return _COPY[key][language]
