"""initial schema

Revision ID: 700b27b6dfe1
Revises: 
Create Date: 2026-08-06 08:30:43.225058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700b27b6dfe1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('client_email', sa.String(length=320), nullable=False),
    sa.Column('client_phone', sa.String(length=40), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('client_goal', sa.Text(), nullable=True),
    sa.Column('attorney_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_owner_user_id'), 'cases', ['owner_user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_case_id'), 'ai_conversations', ['case_id'], unique=False)
    op.create_table('case_assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('loan_balance', sa.Float(), nullable=False),
    sa.Column('jointly_owned', sa.Boolean(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_assets_case_id'), 'case_assets', ['case_id'], unique=False)
    op.create_table('case_debts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('creditor', sa.String(length=200), nullable=False),
    sa.Column('debt_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('delinquent_amount', sa.Float(), nullable=False),
    sa.Column('collateral', sa.String(length=300), nullable=True),
    sa.Column('collection_lawsuit', sa.Boolean(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_debts_case_id'), 'case_debts', ['case_id'], unique=False)
    op.create_table('case_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('evidence_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.create_table('case_expenses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_expenses_case_id'), 'case_expenses', ['case_id'], unique=False)
    op.create_table('case_household',
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('marital_status', sa.String(length=60), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('filing_jointly', sa.Boolean(), nullable=False),
    sa.Column('housing_status', sa.String(length=60), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('urgent_collection_action', sa.Boolean(), nullable=False),
    sa.Column('recent_property_transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_income',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_income_case_id'), 'case_income', ['case_id'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    op.create_table('case_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_tasks_case_id'), 'case_tasks', ['case_id'], unique=False)
    op.create_table('case_timeline',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_timeline_case_id'), 'case_timeline', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_timeline_case_id'), table_name='case_timeline')
    op.drop_table('case_timeline')
    op.drop_index(op.f('ix_case_tasks_case_id'), table_name='case_tasks')
    op.drop_table('case_tasks')
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_case_income_case_id'), table_name='case_income')
    op.drop_table('case_income')
    op.drop_table('case_household')
    op.drop_index(op.f('ix_case_expenses_case_id'), table_name='case_expenses')
    op.drop_table('case_expenses')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_index(op.f('ix_case_debts_case_id'), table_name='case_debts')
    op.drop_table('case_debts')
    op.drop_index(op.f('ix_case_assets_case_id'), table_name='case_assets')
    op.drop_table('case_assets')
    op.drop_index(op.f('ix_ai_conversations_case_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_cases_owner_user_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('users')
    # ### end Alembic commands ###
